# Site settings
title: Succinct Data Structures for NLP-at-Scale
tag_text: Good Clean Read
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
