# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Succinct Data Structures for NLP-at-Scale
authors:             'Matthias Petri and Trevor Cohn'
url:                 https://mpetri.github.io/coling16-tutorial/
baseurl:             ''
font-awesome-include: true # make this false if you don't need font-awesome

# Custom vars
version:             1.0.0

gems:
   - jekyll-coffeescript
   - jekyll-paginate
   - jekyll-gist
   
exclude: ["README.md","LICENSE.md","about.md"]